export const personalData = {
  name: "Basiturraza",
  lastName: "Taji",
  fullName: "Basiturraza Taji",
  roles: [
    "Full Stack Developer",
    "React Developer",
    "Software QA Specialist",
    "Creative Designer",
    "Python Developer",
  ],
  tagline:
    "I don't just write code; I architect digital solutions that survive the real world.",
  bio: `Currently pursuing a BCA (2023-2026) at VMV College, I occupy the rare intersection of Backend Engineering and Visual Storytelling. My approach is rooted in Consultancy-Driven Development—I solve the business logic before I touch the keyboard.`,
  devPhilosophy: `I specialize in Legacy Refactoring. If your PHP environment is sluggish or insecure, I rebuild it into a modular, high-speed ecosystem designed for 2026 standards.`,
  creativeEdge: `With deep expertise in Adobe & CorelDRAW, I bridge the gap between Figma mockups and production code, ensuring 100% brand consistency from print to pixel.`,
  qaStatement: `Beyond the build, I am a Software QA Strategist. I hunt for edge-case bugs that standard automation misses. By stress-testing my own builds—like the Rental Management System—I ensure every deployment is production-hardened.`,
  closingStatement: `Whether it's building a custom CRM from scratch or troubleshooting complex software logic, I provide a consultancy-first mindset that prioritizes scalability, security, and superior user experience.`,
  location: "Nagpur, MH, India",
  address: "NIT Block A/20, Nandanvan, Nagpur - 440009, IN",
  phone: "+91 90226 95311",
  whatsapp: "919022695311",
  email: "basiturraza@gmail.com",
  github: "https://github.com/KernelShellFail",
  githubUsername: "KernelShellFail",
  education: "BCA (2023-2026), VMV College",
  availableYear: 2026,
  profileImage: "/images/me.png",
  stats: {
    yearsExperience: 3,
    projectsCompleted: 10,
    technologiesUsed: 15,
    githubContributions: 500,
  },
  socialLinks: {
    github: "https://github.com/KernelShellFail",
    email: "mailto:basiturraza@gmail.com",
    whatsapp: "https://wa.me/919022695311",
  },
} as const;
